### ISSUE TITLE
Нельзя хранить в статике активити

### ISSUE THREAD

**Issue by neikila** [wenzbr/dz_tp#3]
https://github.com/wenzbr/dz_tp/blob/0fe29f0e262d2122830c4dfcd3afb08177381788/app/src/main/java/com/vbb/dz_tp/Fragments/TableFragment.java#L24

Это потенциально ведет к утечке памяти.
Замени статику на вот такое обращение ((FragmentAdapter)getActivity()).loadData(...)

**Comment by wenzbr** [comment]
Решено
