### ISSUE TITLE
Неоптимальный вызов

### ISSUE THREAD

**Issue by neikila** [wenzbr/dz_tp#4]
https://github.com/wenzbr/dz_tp/blob/0fe29f0e262d2122830c4dfcd3afb08177381788/app/src/main/java/com/vbb/dz_tp/Fragments/TableFragment.java#L72

Андрей рассказывал на лекции, что там есть много методов более оптимальных чем notifyDataSetChanged
В данном случае тебя устроил бы notifyItemInserted

**Comment by wenzbr** [comment]
Исправлено
